# Build settings
remote_theme: jekyll/minima

# Site settings
title: "Tyson's GitHub Portfolio"
author:
  name: Tyson Bryant
  email: bryantty@oregonstate.edu
description: Peruse a collection of my school projects.
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/tysonfromearth" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/tysonfromearth/" }
  skin: auto
header_pages:
  - index.md
  - about.md
